Inclui sugestões de ferramentas livres
okfn-brasil/embaixadoras pull request #103
Opened 2022-02-13 20:30 UTC by augusto-herrmann

alternativas às big tech. Muita gente nem sabe que existem alternativas às
grandes plataformas e que podem respeitar melhor a sua privacidade e
dar maior autonomia às comunidades.

Por isso, é importante destacá-las no guia, para quem se importar com
essas questões e ter alternativas para montar o seu evento do Open Data
Day.

2022-03-18 20:51 UTC, giuliocc requested changes
Muito obrigado pelas indicações @augusto-herrmann ! Fiz algumas sugestões para alterar um pouco a estrutura do texto e melhorar um pouco a leitura.

2022-03-18 20:51 UTC, giuliocc commented on Guia-ODD/Guia-ODD2022.md
> +- Ferramentas de streaming (preferencialmente aquelas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switching.software/replace/zoom/), como [Jitsi Meet](https://jits
Como haviam muitas sugestões, acho que podemos quebrar em tópicos aninhados. Também sugiro mudar um pouco o texto para a quebra funcionar melhor

```suggestion
- Ferramentas de streaming
    - Ferramentas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switching.software/replace/zoom/) são preferencialmente indicadas: [Jitsi Meet](https://jitsi.org/), [Big Blue Button](https://bigbluebutton.org/), [Jami](https://jami.net/), [OBS Studio](https://obsproject.com/pt-br), [Matrix](https://matrix.org/) e [PeerTube](https://joinpeertube.org/)
    - Caso as alternativas anteriores não consigam ser utilizadas também há alternativas fechadas: Zoom, StreamYard, Google Meet, YouTube
```

2022-03-18 20:51 UTC, giuliocc commented on Guia-ODD/Guia-ODD2022.md
> +Assim que tiver um local definido, disponibilize um link com mais informações (preferencialmente em ferramentas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switchi
Faz bem mais sentido mover o parágrafo para fora dos tópicos mesmo!

Na mesma linha da sugestão anterior:
```suggestion
Assim que tiver um local definido, disponibilize um link com mais informações ou mesmo um formulário de inscrição e cadastre o evento no [site oficial do ODD 2022](https://opendataday.org/pt_br/). Dessa forma, mais pessoas encontrarão o evento local com facilidade.

- Ferramentas para eventos
    - Ferramentas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switching.software/replace/meetup/) são preferencialmente indicadas: [Mobilizon](https://joinmobilizon.org/en/), [Gath.io](https://gath.io/), [Gancio](https://gancio.org/), ou [GetTogether](https://gettogether.community/)
    - Caso as alternativas anteriores não consigam ser utilizadas também há alternativas fechadas: evento no Facebook (limitação: só acessa quem tem conta), Eventbrite, Sympla, MeetUp
```

2022-03-22 11:48 UTC, ArianeCamilo commented on Guia-ODD/Guia-ODD2022.md
> +- Ferramentas de streaming (preferencialmente aquelas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switching.software/replace/zoom/), como [Jitsi Meet](https://jits
Oi, pessoal!

Vou discordar um pouco da redação dos trechos propostos pois, como vocês sabem, temos construído uma relação mais abrangente com a nossa comunidade em relação a preferências por ferramentas e canais. As sugestões baseadas em software livre são muito bem-vindas, mas não podemos constranger as pessoas que porventura não as conheçam/não se sintam confortáveis para utilizá-las e prefiram seguir com os softwares mais conhecidos e amplamente utilizados (ainda que, infelizmente, sejam proprietários). 

```suggestion
- Ferramentas de streaming
    - Ferramentas baseadas em software livre são preferencialmente indicadas: [Jitsi Meet](https://jitsi.org/), [Big Blue Button](https://bigbluebutton.org/), [Jami](https://jami.net/), [OBS Studio](https://obsproject.com/pt-br), [Matrix](https://matrix.org/) e [PeerTube](https://joinpeertube.org/)
    - Ferramentas de software proprietário: [Zoom](https://zoom.us/), [StreamYard](https://streamyard.com/), [Google Meet](https://meet.google.com/), [YouTube](https://www.youtube.com/)
```

2022-03-22 11:48 UTC, ArianeCamilo commented on Guia-ODD/Guia-ODD2022.md
> +Assim que tiver um local definido, disponibilize um link com mais informações (preferencialmente em ferramentas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switchi
Seguindo a linha do comentário anterior:

```suggestion
Assim que tiver um local definido, disponibilize um link com mais informações ou mesmo um formulário de inscrição e cadastre o evento no [site oficial do Open Data Day](https://opendataday.org/pt_br/). Dessa forma, mais pessoas encontrarão o evento local com facilidade.
- Ferramentas para eventos
    - Ferramentas baseadas em software livre são preferencialmente indicadas: [Mobilizon](https://joinmobilizon.org/en/), [Gath.io](https://gath.io/), [Gancio](https://gancio.org/), ou [GetTogether](https://gettogether.community/)
    - Ferramentas de software proprietário: evento no Facebook (limitado a usuários com conta na plataforma), [Eventbrite](https://www.eventbrite.com.br/), [Sympla](https://www.sympla.com.br/), [MeetUp](https://www.meetup.com/pt-BR/)
```

2022-03-22 12:29 UTC, augusto-herrmann commented on Guia-ODD/Guia-ODD2022.md
> +- Ferramentas de streaming (preferencialmente aquelas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switching.software/replace/zoom/), como [Jitsi Meet](https://jits
Boa ideia, @giuliocc. Dividindo fica mais fácil a leitura. Porém, nem todas as ferramentas citadas são de streaming. Algumas são de videochamadas, outras de chat em texto, outras são mesmo de streaming. Vou tentar organizar melhor fazendo mais subdivisões.

@ArianeCamilo, esse texto pode ser para muita gente a primeira vez que a pessoa ouve falar em alguma ferramenta, mesmo em relação às proprietárias. Por exemplo, antes deste texto eu mesmo nunca havia ouvido falar em StreamYard. Não é porque a ferramenta é proprietária que ela vai ser mais conhecida ou a pessoa vai se sentir menos "constrangida" a utilizá-la. Entendo que devemos apontar todas as alternativas, mas também explicar as consequências de cada escolha, inclusive no que se refere à liberdade do usuário e coleta de dados.

Vou fazer um novo commit com a proposta.

2022-03-22 20:44 UTC, augusto-herrmann commented on Guia-ODD/Guia-ODD2022.md
> +- Ferramentas de streaming (preferencialmente aquelas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switching.software/replace/zoom/), como [Jitsi Meet](https://jits
Atualizado!

2022-03-22 20:48 UTC, augusto-herrmann commented on Guia-ODD/Guia-ODD2022.md
> +Assim que tiver um local definido, disponibilize um link com mais informações (preferencialmente em ferramentas baseadas em software livre e que [respeitam a privacidade dos usuários](https://switchi
Boas sugestões!

Movi a parte que fala sobre políticas de privacidade para um parágrafo em separado, assim fica mais organizado também.

Só para ilustrar como isso pode fazer as pessoas desistirem de participar, no ano passado eu não participei de um evento do Open Data Day somente porque tinha como condição aceitar os termos de serviço e política de privacidade do Discord. Essa plataforma tem [ranking nota E](https://tosdr.org/en/service/536) de privacidade, a mesma nota do Facebook. Até escrevi um [texto](https://herrmann.tech/pt/blog/2021/08/10/por-que-eu-discordo-do-discord-ou-como-escolher-alternativas-com-melhores-termos-de-servico.html) sobre isso.

2022-03-28 15:08 UTC, augusto-herrmann commented
ping @giuliocc @ArianeCamilo 

E agora, podemos seguir?

2022-04-13 17:21 UTC, augusto-herrmann commented
Lembrando deste PR. @giuliocc

2022-05-03 12:09 UTC, augusto-herrmann commented
Ping @ArianeCamilo e @giuliocc

2022-05-16 15:00 UTC, augusto-herrmann commented
@ArianeCamilo e @giuliocc, podemos fazer rebase/merge?

2022-06-01 12:27 UTC, augusto-herrmann commented
@ArianeCamilo e @giuliocc, já deram uma olhada nas modificações que fiz em março?

Acham que agora daria para aceitar?

2022-06-29 15:53 UTC, ogecece requested changes
@augusto-herrmann sugeri aqui uma modificação na escrita dos novos parágrafos trazendo um pouco pra redação a ideia que a @ArianeCamilo colocou nos comentários também. Achei muito legais as novas sugestões!

2022-06-29 15:53 UTC, ogecece commented on Guia-ODD/Guia-ODD2022.md
> +> Consulte sites como [ToS;DR.org](https://tosdr.org/pt_BR/frontpage) e [privacidade.digital](https://www.privacidade.digital/) para ver avaliações de privacidade e resumos das políticas de dados ado
```suggestion
> Se não conhece alguma ferramenta e tiver tempo de testar, tome um tempinho para experimentar. Veja quais atendem melhor sua necessidade (gratuidade, recursos disponíveis, etc.) e a do seu público (necessidade de cadastro, privacidade, etc.) e escolha a mais adequada. 
>
> Outra dica: termos de uso de serviços geralmente são maçantes, então sites como [ToS;DR.org](https://tosdr.org/pt_BR/frontpage) e [privacidade.digital](https://www.privacidade.digital/) existem para ver avaliações de privacidade e resumos das políticas de dados adotadas por cada ferramenta utilizada.
```

2022-06-29 15:54 UTC, giuliocc approved these changes
Para não ter mais o bate-e-volta já que o texto já estava 99%, fiz o commit com as modificações e vou mesclar. Muito obrigado novamente @augusto-herrmann e mais uma vez agradecemos a paciência!

2022-06-29 15:55 UTC, merged

2022-06-30 23:04 UTC, augusto-herrmann reviewed
Ficou ótimo, @giuliocc!