Acrescenta mais referências para fontes de dados
okfn-brasil/embaixadoras pull request #104
Opened 2022-02-13 20:46 UTC by augusto-herrmann

abertos que serão úteis para as atividades de qualquer evento.

O site basedosdados.org está em manutenção, então o substituímos pela iniciativa mais recente, a Base dos Dados Mais.

2022-02-24 14:31 UTC, augusto-herrmann commented
@ArianeCamilo seria legal poder acrescentar essas informações antes da data do Open Data Day 2022. E também o #103 e #104.

2022-03-12 00:50 UTC, augusto-herrmann commented
Infelizmente o ODD já passou sem que fosse feito o merge, mas acho que essas informações ainda podem ser úteis mesmo assim. @ArianeCamilo @trevineju @giuliocc

2022-03-18 18:05 UTC, augusto-herrmann commented
Ping @ArianeCamilo @trevineju @giuliocc

2022-03-18 20:29 UTC, giuliocc requested changes
Novamente, perdão pela demora @augusto-herrmann !

Sim, o PR complementa muito bem o Guia e as adições ainda tem muita valia pois serão passadas ano após ano e há a intenção da OKF de apoiar ODDs ao longo do ano em 2022.

2022-03-18 20:29 UTC, giuliocc commented on Guia-ODD/Guia-ODD2022.md
> +- **Fontes secundárias** - iniciativas não governamentais que sintetizam diversas bases disponíveis: [The Data Hub](https://datahub.io/), [Brasil.io](https://brasil.io), [Base dos Dados Mais](https:/
Aqui eu sugiro manter a referência à Base dos Dados como estava originalmente. Assim, quem ler o Guia terá acesso diretamente à consulta disponível e caso precise utlizar o DW terá na própria interface indicações de como fazer. O que acha?

2022-03-18 20:30 UTC, giuliocc commented
Precisamos apenas resolver o comentário acima e já poderemos mesclar o PR!

2022-03-22 13:18 UTC, augusto-herrmann commented on Guia-ODD/Guia-ODD2022.md
> +- **Fontes secundárias** - iniciativas não governamentais que sintetizam diversas bases disponíveis: [The Data Hub](https://datahub.io/), [Brasil.io](https://brasil.io), [Base dos Dados Mais](https:/
Concordo. Eu havia proposto mudar porque naquele dia o link original estava fora do ar. Mas agora parece que já arrumaram.

2022-03-28 15:07 UTC, augusto-herrmann commented
ping @giuliocc

Está bom agora?

2022-04-13 17:20 UTC, augusto-herrmann commented
Olá, @giuliocc, como vai?

Lembrando deste PR.

2022-05-03 12:10 UTC, augusto-herrmann commented
Ping @giuliocc

2022-05-16 15:00 UTC, augusto-herrmann commented
@giuliocc, podemos fazer rebase/merge?

2022-06-01 12:28 UTC, augusto-herrmann commented
@giuliocc, já deu uma olhada nas modificações que fiz em março?

Acha que agora daria para aceitar?

2022-06-29 15:27 UTC, ogecece approved these changes
Agradecemos a paciência @augusto-herrmann ! Essas adições são muito bem vindas!

2022-06-29 15:27 UTC, merged

2022-06-30 22:28 UTC, augusto-herrmann commented
Obrigado por aceitar o merge, @giuliocc!