Adicionar guia para ODD 2023
okfn-brasil/embaixadoras pull request #123
Opened 2023-02-08 21:53 UTC by rasrbk

Este PR adiciona o Guia para realização de eventos de Open Data Days em 2023.

2023-02-09 22:28 UTC, giuliocc requested changes
Fiz alguns comentários bem pontuais sobre o que foi revisado até o momento. No geral as revisões tão ótimas :)

2023-02-09 22:28 UTC, ogecece commented on Guia-ODD/ODD2023.md
> +    <img src="[https://github.com/okfn-brasil/embaixadoras/blob/main/images/image-guia-ODD2023.png?raw=true]">
Ficou faltando subir a imagem no PR hehe

2023-02-09 22:28 UTC, giuliocc commented on Guia-ODD/ODD2023.md
> +___
Essa barra é necessária?

2023-02-09 22:28 UTC, giuliocc commented on Guia-ODD/ODD2023.md
> +-   Contate funcionários de órgãos de controle (como tribunais de contas) em busca de apoio para analisar as bases de dados
Esse espaçamento é necessário?

2023-02-09 22:28 UTC, giuliocc commented on Guia-ODD/ODD2023.md
> +---
Sem a quebra de linha o renderizador do github entende que a linha 64 é um título (sintaxe de RestructuredText e não de Markdown) e ela renderiza gigante :)
```suggestion

---
```

2023-02-09 22:28 UTC, giuliocc commented on Guia-ODD/ODD2023.md
> +Não é obrigatório desenvolver um produto ou mesmo ter alguma entrega a ser feita ao fim das atividades, por exemplo. O evento também pode ter um caráter informativo e estimulador de discussões pertin
Acho que seria legal destacar essa informação do tema geral do ano. O que acha?

2023-02-09 22:28 UTC, giuliocc commented on Guia-ODD/ODD2023.md
> +    -[Open Knowledge Brasil](bit.ly/discord-ok)
```suggestion
    - [Open Knowledge Brasil](https://go.ok.org.br/discord) 

```

2023-02-09 22:28 UTC, giuliocc commented on Guia-ODD/ODD2023.md
> +Sem roteiro fechado, os participantes discutiram ideias, dividiram-se em dois grupos e dedicaram-se a estudar o nível de volume morto do Sistema Cantareira e os cálculos de consumo das organizações q
Não consegui acessar o link agora. Não sei se ainda é válido

2023-02-13 20:12 UTC, rasrbk commented on Guia-ODD/ODD2023.md
> +___
não, vou revisar os espaços e barras desnecessárias

2023-02-13 20:12 UTC, rasrbk commented on Guia-ODD/ODD2023.md
> +-   Contate funcionários de órgãos de controle (como tribunais de contas) em busca de apoio para analisar as bases de dados
nova versão corrige isso

2023-02-13 20:13 UTC, rasrbk commented on Guia-ODD/ODD2023.md
> +Não é obrigatório desenvolver um produto ou mesmo ter alguma entrega a ser feita ao fim das atividades, por exemplo. O evento também pode ter um caráter informativo e estimulador de discussões pertin
não dei muito destaque para não confundir, dando a entender que todos os eventos precisam se enquadrar nisso

2023-02-13 20:13 UTC, rasrbk commented on Guia-ODD/ODD2023.md
> +    -[Open Knowledge Brasil](bit.ly/discord-ok)
atualizado

2023-02-13 20:13 UTC, rasrbk commented on Guia-ODD/ODD2023.md
> +Sem roteiro fechado, os participantes discutiram ideias, dividiram-se em dois grupos e dedicaram-se a estudar o nível de volume morto do Sistema Cantareira e os cálculos de consumo das organizações q
corrigido

2023-02-13 21:08 UTC, giuliocc commented on Guia-ODD/ODD2023.md
> +Não é obrigatório desenvolver um produto ou mesmo ter alguma entrega a ser feita ao fim das atividades, por exemplo. O evento também pode ter um caráter informativo e estimulador de discussões pertin
beleuza

2023-02-14 21:21 UTC, giuliocc approved these changes
Aprovando!

2023-02-14 21:21 UTC, merged