Adiciona post balanço ODDs 2023
okfn-brasil/embaixadoras pull request #124
Opened 2023-03-20 21:54 UTC by rasrbk

Texto relatando como foram os eventos de Open Data Day realizados em cidades brasileiras em 2023.

2023-03-20 22:07 UTC, trevineju commented on _posts/2023-03-20-balanco-ODDs-2023.md
> +#### Salvador (BA)
Esta seção do texto é "outros", mas este evento foi organizado por vc, pessoa da rede. Acho que poderia reorganizar e migrar esse trecho pra seção anterior junto aos eventos da nossa comunidade.  

Entendi que queria dar destaque ao que as embaixadoras fizeram, então aí poderia ficar por último naquela lista, o que acha?

2023-03-20 22:09 UTC, rasrbk commented on _posts/2023-03-20-balanco-ODDs-2023.md
> +#### Salvador (BA)
acho uma boa ideia

2023-03-20 22:09 UTC, trevineju commented on _posts/2023-03-20-balanco-ODDs-2023.md
> +O valor da mini-bolsa concedida pela Open Knowledge Brasil possibilitou a filmagem das palestras, que serão disponibilizadas em breve no canal do YouTube. O encontro contou também com o apoio das emp
acho que os hiperlinks não foram, como em "canal do YouTube" e outras partes do texto

2023-03-22 19:52 UTC, giuliocc requested changes
Só algumas mudanças, tá bem bom :)

2023-03-22 19:52 UTC, giuliocc commented on _posts/2023-03-20-balanco-ODDs-2023.md
> +O valor da mini-bolsa concedida pela Open Knowledge Brasil possibilitou a filmagem das palestras, que serão disponibilizadas em breve no canal do YouTube. O encontro contou também com o apoio das emp
```suggestion
O valor da mini-bolsa concedida pela Open Knowledge Brasil possibilitou a filmagem das palestras, que serão disponibilizadas no [canal do YouTube](https://www.youtube.com/@dadosabertosdefeira). O encontro contou também com o apoio das empresas Absam, Grupo Voa e Hub Feira. 
```

2023-03-22 19:52 UTC, giuliocc commented on _posts/2023-03-20-balanco-ODDs-2023.md
> +No sábado, 18 de março, a R-Ladies São Paulo realizará o evento “Análise de dados abertos com R – um evento Open Data Day”. O evento reuniu cerca de 40 pessoas, e foi estruturado em 3 blocos. No prim
```suggestion
No sábado, 18 de março, a R-Ladies São Paulo realizaram o evento “Análise de dados abertos com R – um evento Open Data Day”. O evento reuniu cerca de 40 pessoas, e foi estruturado em 3 blocos. No primeiro bloco, aconteceram algumas apresentações, como: o que é a comunidade R-Ladies São Paulo, o que é Open Data Day e o que são Dados Abertos. 
```

2023-03-22 19:52 UTC, giuliocc commented on _posts/2023-03-20-balanco-ODDs-2023.md
> +### **Confira a seguir um resumo das atividades puxadas pelas Embaixadoras de Inovação Cívica da OKBR:**
Minha impressão é que o cabeçalho nível 3 não dá espaçamento embaixo. Sugiro mudar pro 2 (e talvez tirar o negrito). 
```suggestion
## Confira a seguir um resumo das atividades puxadas pelas Embaixadoras de Inovação Cívica da OKBR: 
```

2023-03-22 19:52 UTC, giuliocc commented on _posts/2023-03-20-balanco-ODDs-2023.md
> +A gestora de comunidade no Programa Ciência de Dados para Inovação Cívica da OKBR, Rebeca Almeida, esteve à frente de um encontro em Salvador, juntamente com o Raul Hacker Clube, o Jusbrasil e a comu
![image](https://i.giphy.com/media/l36kU80xPf0ojG0Erg/giphy.gif)

2023-03-22 21:55 UTC, merged