Adiciona post Ariane e atualiza textos anteriores
okfn-brasil/embaixadoras pull request #143
Opened 2023-09-12 21:44 UTC by rasrbk

Adiciona o quinta texto da série Guia de Atuação na Rede e adiciona notas de rodapé nos textos anteriores

2023-09-13 13:39 UTC, trevineju commented on _posts/2023-08-07-abertura-guia-atuacao.md
>  title: 'Guia de Lideranças: embaixadoras compartilham experiências em série de textos e bate-papos'
Vai manter o título como "Guia de Lideranças"? vi que mudou a tag de categoria...

2023-09-13 13:42 UTC, trevineju commented on _posts/2023-08-07-abertura-guia-atuacao.md
> +Nesse sentido, as postagens da série vão trazer relatos e exemplos práticos dessa atuação. Os textos serão publicados ao longo do mês, a cada quinta-feira, a partir do dia 10 de agosto. Ao final, ser
1. Reforço o comentário que não é bom usar os `aqui`. 
2. Assim que o PR for aceito, esse link vai quebrar porque a categoria está deixando de chamar "guia de lideranças". O próprio PR está mudando para "Guia de Atuação"

2023-09-13 14:05 UTC, trevineju commented on _posts/2023-08-10-liderancas-bernardo-baron.md
> +[^1] Esse texto faz parte da série [Guia de Atuação](https://embaixadoras.ok.org.br/guia%20de%20lideran%C3%A7as/inova%C3%A7%C3%A3o%20c%C3%ADvica/2023/08/07/abertura-guia-liderancas/), que consiste em
Vendo a pré-visualização desse post no link do netlify gerado abaixo no bot do PR...
- sugestão a) o "^1" quebrou. Como não tem outros (2, 3,...), acho que o marcador não precisa ser numérico. Poderia ser um asterisco, o que acha? contorna o problema. 
- sugestão b) a possibilidade de sequer colocar um vínculo pra nota de rodapé (ou seja, retirar todos [^1]). A nota poderia simplesmente existir ali numa formatação diferente, como [este exemplo](https://paraibafeminina.com.br/2022/08/05/isencao-para-empresas-3a-tarifa-mais-cara-do-nordeste-e-servico-precario-a-situacao-do-transporte-publico-em-joao-pessoa/) da Paraíba Feminina.

2023-09-13 14:05 UTC, trevineju commented on _posts/2023-08-10-liderancas-bernardo-baron.md
> +[^1] Esse texto faz parte da série [Guia de Atuação](https://embaixadoras.ok.org.br/guia%20de%20lideran%C3%A7as/inova%C3%A7%C3%A3o%20c%C3%ADvica/2023/08/07/abertura-guia-liderancas/), que consiste em
Vou deixar comentado só aqui, mas vale para todos os posts com esse mesmo recurso.

2023-09-13 14:07 UTC, trevineju commented on _posts/2023-08-29-liderancas-adolfo-guimaraes copy.md
> +[^1] Esse texto faz parte da série [Guia de Atuação](https://embaixadoras.ok.org.br/guia%20de%20lideran%C3%A7as/inova%C3%A7%C3%A3o%20c%C3%ADvica/2023/08/07/abertura-guia-liderancas/), que consiste em
Aliás, aqui no post do Adolfo, a quebra `---` foi adicionada, o que diferenciou dos outros rodapés. Pareceu legal. Poderia ter nos outros também.

2023-09-13 14:08 UTC, trevineju commented on _posts/2023-09-12-liderancas-ariane-alves.md
> +    - Guia de Lideranças
```suggestion
    - Guia de Atuação
```

2023-09-13 14:08 UTC, trevineju commented on _posts/2023-09-12-liderancas-ariane-alves.md
> +>*"todo esse conhecimento sobre Inovação Cívica que adquirimos ao longo das atividades não pode ficar restrito aos nossos espaços. Precisamos multiplicar as ideias e ações, ampliando o alcance a outr
Neste, faltou o rodapé

2023-09-13 14:10 UTC, trevineju commented on _posts/2023-09-12-liderancas-ariane-alves.md
> +>*"todo esse conhecimento sobre Inovação Cívica que adquirimos ao longo das atividades não pode ficar restrito aos nossos espaços. Precisamos multiplicar as ideias e ações, ampliando o alcance a outr
```suggestion
>*"todo esse conhecimento sobre Inovação Cívica que adquirimos ao longo das atividades não pode ficar restrito aos nossos espaços. Precisamos multiplicar as ideias e ações, ampliando o alcance a outros públicos e descentralizando os saberes por meio de encontros, eventos e formações."*

[^1] Esse texto faz parte da série [Guia de Atuação](https://embaixadoras.ok.org.br/guia%20de%20lideran%C3%A7as/inova%C3%A7%C3%A3o%20c%C3%ADvica/2023/08/07/abertura-guia-liderancas/), que consiste em uma série de postagens com depoimentos de pessoas da rede, compartilhando experiências e formas de atuação dentro do cenário de inovação cívica brasileiro. O objetivo é compartilhar conhecimentos, em especial com as novas embaixadoras, bem como reforçar a importância da atuação em comunidade.
```

Faltou o rodapé. Adicionei a sugestão conforme está nos outros casos, por enquanto. Mas o apontamento feito sobre o rodapé em outro comentário serve aqui tb.

2023-09-13 14:13 UTC, trevineju commented on _posts/2023-08-07-abertura-guia-atuacao.md
> +Nesse sentido, as postagens da série vão trazer relatos e exemplos práticos dessa atuação. Os textos serão publicados ao longo do mês, a cada quinta-feira, a partir do dia 10 de agosto. Ao final, ser
```suggestion
Nesse sentido, [as postagens da série vão trazer relatos](https://embaixadoras.ok.org.br/category/guia-de-lideran%C3%A7as/) e exemplos práticos dessa atuação. Os textos serão publicados ao longo do mês, a cada quinta-feira, a partir do dia 10 de agosto. Já as conversas para troca de experiências serão uma atividade interna da Rede.
```

1. Reforço o comentário que não é bom usar `aqui`, pq precisa ser mais semântico o trecho que vincula o link. Deixei uma sugestão. 

2. Assim que o PR for aceito, esse link vai quebrar porque a categoria está deixando de chamar "guia de lideranças". O próprio PR está mudando para "Guia de Atuação"

2023-09-13 14:15 UTC, trevineju commented on _posts/2023-09-12-liderancas-ariane-alves.md
> +Posso iniciar este relato afirmando que tenho uma posição bastante privilegiada ao falar sobre a Rede de Pessoas Embaixadoras de Inovação Cívica: acompanhei o projeto desde o início e passei pelos tr
```suggestion
*Precisamos multiplicar as ideias e ações, ampliando o alcance a outros públicos e descentralizando os saberes por meio de encontros, eventos e formações.*

Por *Ariane Alves* [^1]

Posso iniciar este relato afirmando que tenho uma posição bastante privilegiada ao falar sobre a Rede de Pessoas Embaixadoras de Inovação Cívica: acompanhei o projeto desde o início e passei pelos três primeiros ciclos de integração dos participantes como gestora dessa rica comunidade — papel que hoje é muito bem ocupado pela Rebeca Almeida. 
```

Os outros posts tinham a autoria no corpo.

2023-09-13 14:32 UTC, trevineju requested changes
Acredito que essa questão de trocar o nome da ação de "Guia de Lideranças" para "Guia de Atuação" ainda está com alguns pontos soltos. 

## Importante: 
Algumas modificações do PR são delicadas. Vou usar o post da Olivia de exemplo. Ele tem hoje, no ar, essas características:  
1. está na categoria "guia de lideranças": `/guia%20de%20lideran%C3%A7as/`
2. está na categoria "inovação cívica": `/inova%C3%A7%C3%A3o%20c%C3%ADvica/`
3. marcado com certa data: `/2023/08/24/`
4. e o nome do arquivo é específico: `/liderancas-olivia-boretti/`

Tudo isso junto faz com que a URL seja (perceba os trechos): 
https://embaixadoras.ok.org.br/guia%20de%20lideran%C3%A7as/inova%C3%A7%C3%A3o%20c%C3%ADvica/2023/08/24/liderancas-olivia-boretti/

Se qualquer parte disso mudar, o link acima quebra. Com o PR mudando o título da categoria ("Guia de Lideranças"  -> "Guia de Atuação"), os links todos mudam. Uma vez que o PR seja aceito, o link vai ser algo como: `
embaixadoras.ok.org.br/ {guia de atuação} /inova%C3%A7%C3%A3o%20c%C3%ADvica/2023/08/24/liderancas-olivia-boretti/` 

Isso vale a pena? implica que em qualquer lugar que tenha sido enviado (emails, comunicações, mensagens) o link estará quebrado. Mas se não estiver muito divulgado ou se pode ser corrigido (por exemplo, avisando que os links mudaram) pode não ser um problema e valer a pena. Está em jogo ponderar qual o melhor título, como organizar melhor no repositório e homogenizar as modificações X lidar com as consequências e o esforço posterior que precisa ser feito.

Já que essa é a situação e se for decidido que é preferível seguir com a mudança proposta, acho que o nome dos arquivos também precisam ser mudados, modificando o `lideranças` (conforme expliquei acima, o nome do arquivo tb compõe o link, então isso tb quebraria a referência; aqui valeria a pena já que muda tudo junto de uma única vez
![image](https://github.com/okfn-brasil/embaixadoras/assets/44185775/4ab34e02-9883-4e64-8e2e-ac055a6e2aad)

2023-09-13 15:01 UTC, trevineju commented on _posts/2023-08-07-abertura-guia-atuacao.md
>  title: 'Guia de Lideranças: embaixadoras compartilham experiências em série de textos e bate-papos'
```suggestion
title: 'Guia de Atuação: embaixadoras compartilham experiências em série de textos e bate-papos'
```

2023-09-13 18:28 UTC, rasrbk commented on _posts/2023-08-10-liderancas-bernardo-baron.md
> +[^1] Esse texto faz parte da série [Guia de Atuação](https://embaixadoras.ok.org.br/guia%20de%20lideran%C3%A7as/inova%C3%A7%C3%A3o%20c%C3%ADvica/2023/08/07/abertura-guia-liderancas/), que consiste em
faz sentido, eu vou seguir a sugestão b.

2023-09-18 14:33 UTC, trevineju approved these changes

2023-09-18 14:33 UTC, merged

2023-09-18 18:14 UTC, rasrbk commented
Obrigada, @trevineju!