Adiciona eventos de ODDs 2023
okfn-brasil/embaixadoras pull request #145
Opened 2023-09-16 00:55 UTC by rasrbk

Adiciona eventos de ODDs na página de eventos.

2023-09-20 13:59 UTC, ogecece requested changes

2023-09-20 13:59 UTC, ogecece commented on _events/2023-03-26-Open-Data-Day-2023.md
> +subtitle: Open Data Day 2023 Porto Alegre
Não entendi o "Porto Alegre" no título
```suggestion
subtitle: Eventos no Open Data Day 2023
```

2023-09-20 13:59 UTC, ogecece commented on _events/2023-03-26-Open-Data-Day-2023.md
> +image_path: /images/events/2023-03-26-ODD-Recife-PE.png
No preview todas as imagens estão quebradas, inclusive essa do banner

2023-09-20 14:02 UTC, rasrbk commented on _events/2023-03-26-Open-Data-Day-2023.md
> +image_path: /images/events/2023-03-26-ODD-Recife-PE.png
eu não entendi porque, achei que era porque ainda não tinham subido de fato pro repositório.

2023-10-10 18:36 UTC, ogecece approved these changes

2023-10-10 18:39 UTC, merged