informacoes_alison_lima
okfn-brasil/embaixadoras pull request #38
Opened 2019-11-10 23:49 UTC by AlisonRLima

2019-11-11 11:50 UTC, giovanisleite requested changes
- Mudar o nome da imagem substituindo os espaços por `_`
- O nome do arquivo dentro da pasta `_staff_members/` tem que ter a extensão `.md`

2019-11-11 11:51 UTC, giovanisleite commented on _staff_members/alison_lima
> +image_path:images/team/foto perfil alison.jpg
```suggestion
image_path: images/team/alison_lima.jpg
```

2019-11-11 21:13 UTC, AlisonRLima commented on _staff_members/alison_lima
> +image_path:images/team/foto perfil alison.jpg
tentei fazer as alterações, mas não sei se deu certo

2019-11-12 17:13 UTC, giovanisleite commented on _staff_members/alison_lima
> +image_path:images/team/foto perfil alison.jpg
Faltou o espaço entre `:` e o `i`

2020-04-16 15:09 UTC, closed without merging