Inserção dos dados Guilherme Augusto
okfn-brasil/embaixadoras pull request #40
Opened 2019-11-11 13:51 UTC by guilhermeaugusto9

2019-11-11 14:24 UTC, giovanisleite requested changes
Para aparecer na lista tem que renomear o arquivo `_staff_members/guilherme_augusto` para `_staff_members/guilherme_augusto.md`

2019-11-11 14:29 UTC, guilhermeaugusto9 reviewed
Renomeado, não sei se funcionou haha

2019-11-11 14:36 UTC, giovanisleite requested changes

2019-11-11 14:36 UTC, giovanisleite commented on _staff_members/guilherme_augusto.md
> +twitter: @guilherme.augusto9g
```suggestion
twitter: guilherme.augusto9g
```
Não precisa do `@`, esse user do tt não existe

2019-11-11 14:45 UTC, guilhermeaugusto9 commented on _staff_members/guilherme_augusto.md
> +twitter: @guilherme.augusto9g
Alterado

2019-11-12 20:53 UTC, giovanisleite commented on _staff_members/guilherme_augusto.md
> +name: Guilherme Augusto
```suggestion
---
name: Guilherme Augusto
```

2019-11-12 20:53 UTC, giovanisleite commented on _staff_members/guilherme_augusto.md
> +twitter: Augusto9G
```suggestion
twitter: Augusto9G
---
```

2019-11-12 22:54 UTC, giovanisleite approved these changes
:rocket:

2019-11-14 12:27 UTC, merged