Dados - Lucas Prado
okfn-brasil/embaixadoras pull request #61
Opened 2019-12-12 15:24 UTC by lucasprado84

Upload da foto e dados.

2019-12-12 15:45 UTC, giovanisleite requested changes
Boa! Está funcionando.

Acabou indo uma foto a mais, se puder deletar a foto que **não** está na pasta `images/team/`

2019-12-12 18:37 UTC, lucasprado84 commented
Já deletei a Avatar Lucas Prado (1).jpg

2019-12-12 18:38 UTC, lucasprado84 commented
Olhei nas outras pastas, mas não encontrei nenhuma outra foto.

2019-12-12 18:48 UTC, lucasprado84 commented
Deletei lá...

2019-12-13 12:39 UTC, giovanisleite approved these changes

2019-12-13 15:31 UTC, merged